

-- Tabla de deportes
CREATE TABLE Sport (
  sport_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sport_name VARCHAR2(100) NOT NULL UNIQUE,
  ball_image_path VARCHAR2(255)
);

-- Tabla de equipos
CREATE TABLE Team (
  team_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  team_name VARCHAR2(100) NOT NULL UNIQUE,
  photo_path VARCHAR2(255),
  sport_id NUMBER NOT NULL,
  CONSTRAINT fk_team_sport FOREIGN KEY (sport_id) REFERENCES Sport(sport_id)
);

-- Tabla de torneos
CREATE TABLE Tournament (
  tournament_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tournament_name VARCHAR2(100) NOT NULL,
  sport_id NUMBER NOT NULL,
  team_count NUMBER NOT NULL,
  match_time_minutes NUMBER NOT NULL,
  start_date DATE DEFAULT SYSDATE,
  CONSTRAINT fk_tournament_sport FOREIGN KEY (sport_id) REFERENCES Sport(sport_id)
);

-- Relación equipos inscritos en torneos
CREATE TABLE Tournament_Team (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tournament_id NUMBER NOT NULL,
  team_id NUMBER NOT NULL,
  position NUMBER,
  CONSTRAINT fk_tt_tournament FOREIGN KEY (tournament_id) REFERENCES Tournament(tournament_id),
  CONSTRAINT fk_tt_team FOREIGN KEY (team_id) REFERENCES Team(team_id),
  CONSTRAINT uq_tt UNIQUE (tournament_id, team_id)
);

-- Tabla de partidos
CREATE TABLE Match (
  match_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tournament_id NUMBER NOT NULL,
  team1_id NUMBER NOT NULL,
  team2_id NUMBER NOT NULL,
  scheduled_time DATE,
  status VARCHAR2(20) DEFAULT 'PENDING', -- PENDING, FINISHED
  winner_id NUMBER,
  CONSTRAINT fk_match_tournament FOREIGN KEY (tournament_id) REFERENCES Tournament(tournament_id),
  CONSTRAINT fk_match_team1 FOREIGN KEY (team1_id) REFERENCES Team(team_id),
  CONSTRAINT fk_match_team2 FOREIGN KEY (team2_id) REFERENCES Team(team_id),
  CONSTRAINT fk_match_winner FOREIGN KEY (winner_id) REFERENCES Team(team_id)
);

-- Resultado del partido
CREATE TABLE Match_Result (
  result_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  match_id NUMBER NOT NULL,
  team_id NUMBER NOT NULL,
  goals NUMBER DEFAULT 0,
  extra_points NUMBER DEFAULT 0,
  CONSTRAINT fk_result_match FOREIGN KEY (match_id) REFERENCES Match(match_id),
  CONSTRAINT fk_result_team FOREIGN KEY (team_id) REFERENCES Team(team_id)
);

